<?php
// $Id: xoops_version.php
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
//  Author:  Mithrandir                                                      //

$modversion['name'] = _CR_MI_NAME;
$modversion['version'] = 1.09;
$modversion['description'] = _CR_MI_DESC;
$modversion['credits'] = "The XOOPS Project";
$modversion['help'] = "classroom.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/cr_slogo.png";
$modversion['dirname'] = "obs_classroom";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "cr_school";
$modversion['tables'][1] = "cr_division";
$modversion['tables'][2] = "cr_classroom";
$modversion['tables'][3] = "cr_block";
$modversion['tables'][4] = "cr_class";
$modversion['tables'][5] = "cr_classblock";
$modversion['tables'][6] = "cr_lessonplan";
$modversion['tables'][7] = "cr_lessonplanblock";
$modversion['tables'][8] = "cr_homework";
$modversion['tables'][9] = "cr_value";
$modversion['tables'][10] = "cr_rss";
$modversion['tables'][11] = "cr_question";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Templates
$modversion['templates'][1]['file'] = 'cr_overview.html';
$modversion['templates'][1]['description'] = 'List Schools';
$modversion['templates'][2]['file'] = 'cr_school.html';
$modversion['templates'][2]['description'] = 'List Divisions in School';
$modversion['templates'][3]['file'] = 'cr_division.html';
$modversion['templates'][3]['description'] = 'List Classrooms in Division';
$modversion['templates'][4]['file'] = 'cr_classroom.html';
$modversion['templates'][4]['description'] = 'List Classes in Classroom';
$modversion['templates'][5]['file'] = 'cr_class.html';
$modversion['templates'][5]['description'] = 'Display Class';
$modversion['templates'][6]['file'] = 'cr_block.html';
$modversion['templates'][6]['description'] = 'Display Block';
$modversion['templates'][7]['file'] = 'cr_blocktype_textfield.html';
$modversion['templates'][7]['description'] = 'Show a textfield block';
$modversion['templates'][8]['file'] = 'cr_blocktype_lessonplan.html';
$modversion['templates'][8]['description'] = 'Show a lessonplan block';
$modversion['templates'][9]['file'] = 'cr_blocktype_link.html';
$modversion['templates'][9]['description'] = 'Show a web link block';
$modversion['templates'][10]['file'] = 'cr_blocktype_classrules.html';
$modversion['templates'][10]['description'] = 'Show a class rules block';
$modversion['templates'][11]['file'] = 'cr_blocktype_homework.html';
$modversion['templates'][11]['description'] = 'Show a homework block';
$modversion['templates'][12]['file'] = 'cr_blocktype_downloads.html';
$modversion['templates'][12]['description'] = 'Show a handout downloads block';
$modversion['templates'][13]['file'] = 'cr_blocktype_quote.html';
$modversion['templates'][13]['description'] = 'Show a random quote block';
$modversion['templates'][14]['file'] = 'cr_blocktype_image.html';
$modversion['templates'][14]['description'] = 'Show a random image block';
$modversion['templates'][15]['file'] = 'cr_blocktype_rss.html';
$modversion['templates'][15]['description'] = 'Show a RSS Feed block';
$modversion['templates'][16]['file'] = 'cr_blocktype_quiz.html';
$modversion['templates'][16]['description'] = 'Show a Practice Quiz block';
$modversion['templates'][17]['file'] = 'cr_interact_quiz.html';
$modversion['templates'][17]['description'] = 'Show results from a Practice Quiz block';
$modversion['templates'][18]['file'] = 'cr_blocktype_spelling.html';
$modversion['templates'][18]['description'] = 'Show a Spelling List block';
$modversion['templates'][19]['file'] = 'cr_blocktype_spelling_details.html';
$modversion['templates'][19]['description'] = 'Show a Spelling Term Explained';
$modversion['templates'][20]['file'] = 'cr_blocktype_contact.html';
$modversion['templates'][20]['description'] = 'Show a Contact Teacher block';

// Blocks
$modversion['blocks'][1]['file'] = "edit_mode.php";
$modversion['blocks'][1]['name'] = _CR_MI_BL_EDITMODE;
$modversion['blocks'][1]['description'] = "Sets edit mode on/off";
$modversion['blocks'][1]['show_func'] = "b_editmode_show";
$modversion['blocks'][1]['template'] = 'cr_block_editmode.html';

// Classroom Blocktypes
$modversion['blocktypes'][1]['name'] = "Textfield";
$modversion['blocktypes'][2]['name'] = "Lessonplan";
$modversion['blocktypes'][3]['name'] = "Link";
$modversion['blocktypes'][4]['name'] = "Classrules";
$modversion['blocktypes'][5]['name'] = "Homework";
$modversion['blocktypes'][6]['name'] = "Downloads";
$modversion['blocktypes'][7]['name'] = "Quote";
$modversion['blocktypes'][8]['name'] = "Image";
$modversion['blocktypes'][9]['name'] = "Rss";
$modversion['blocktypes'][10]['name'] = "Quiz";
$modversion['blocktypes'][11]['name'] = "SpellingList";
$modversion['blocktypes'][12]['name'] = "Contact";

// Menu
$modversion['hasMain'] = 1;

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "cr_search";

$modversion['config'][1]['name'] = 'head_group';
$modversion['config'][1]['title'] = '_MI_HEADGROUP';
$modversion['config'][1]['description'] = '_MI_HEADGROUPDESC';
$modversion['config'][1]['formtype'] = 'group_multi';
$modversion['config'][1]['valuetype'] = 'array';
$modversion['config'][1]['default'] = array(1);

$modversion['config'][2]['name'] = 'director_group';
$modversion['config'][2]['title'] = '_MI_DIRECTORGROUP';
$modversion['config'][2]['description'] = '_MI_DIRECTORGROUPDESC';
$modversion['config'][2]['formtype'] = 'group_multi';
$modversion['config'][2]['valuetype'] = 'array';
$modversion['config'][2]['default'] = array(1);

$modversion['config'][3]['name'] = 'teacher_group';
$modversion['config'][3]['title'] = '_MI_TEACHERGROUP';
$modversion['config'][3]['description'] = '_MI_TEACHERGROUPDESC';
$modversion['config'][3]['formtype'] = 'group_multi';
$modversion['config'][3]['valuetype'] = 'array';
$modversion['config'][3]['default'] = array(1);

$modversion['config'][4]['name'] = 'frontpagetext';
$modversion['config'][4]['title'] = '_MI_FRONTPAGETEXT';
$modversion['config'][4]['description'] = '_MI_FRONTPAGETEXT_DESC';
$modversion['config'][4]['formtype'] = 'textarea';
$modversion['config'][4]['valuetype'] = 'text';
$modversion['config'][4]['default'] = "";

$modversion['config'][5]['name'] = 'max_file_size';
$modversion['config'][5]['title'] = '_MI_MAXFILESIZE';
$modversion['config'][5]['description'] = '_MI_MAXFILESIZE_DESC';
$modversion['config'][5]['formtype'] = 'text';
$modversion['config'][5]['valuetype'] = 'int';
$modversion['config'][5]['default'] = "1024";
?>